# Generated by Django 6.0.7 on 2026-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
