# Generated by Django 6.0.7 on 2026-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_product_image_orderitem_cost_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
