# Generated by Django 6.0.7 on 2026-08-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_orderitem_cost_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('sc_pwd', 'SC / PWD')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
